### ISSUE TITLE
Not working with minimal example

### ISSUE THREAD

**Issue by hoschi** [jcoreio/react-media-material-ui#2]
I tried to get it to work with Codesandbox but it doesn't: https://codesandbox.io/s/m4x1nm2p88
It should show "true" for breakpoint "xs" as this starts at `0`. Did I missed something obvious?

**Comment by jedwards1211** [comment]
@hoschi sorry for the really late reply, I must have missed this because my dad passed away around that time.  This was a bug, and I fixed it in `2.0.1`.  Once I updated the package in your sandbox it shows "true".  Thanks for reporting this!
